baseurl = "https://example.com/"
languageCode = "en-us"
defaultContentLanguage = "en" # en / zh-CN / ... (This field determines which i18n file to use)
title = "Hugo W3 Simple Theme"
theme = "hugo-w3-simple"
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
paginate = 12 #gridstyle use 3 column. so should be 3,6,9,12,15....

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[[menu.main]]
    name = "All Posts"
    url = "/allposts/"
    weight = 5


[params]
    relatedPosts = true
    gridstyle = true  # list post with grid style. If false then simple list
    readingtime = true  #display reading time
    firstpic = true  # display first picture as thumbnail if no thumbnail set. For gridstyle only
    socialshare = true
    socialicon = true
    googletranslate = true
    searchfunction = true #If true, it will only display search button but real search function is not included in example site because it need server-side app. To see the demo please visit https://jesselau.com
    description = "Hugo W3 Simple Theme"
    onesignalid = ""  #one signal push app id
    logotext = "HUGO W3 SIMPLE" # logo text
    footer = "&copy; [John Doe](https://johndoe.com) 2018 | [Github](https://github.com/johndoe) | [Twitter](https://twitter.com/johndoe)  | [RSS](/index.xml)"


[params.social]  # Set your social account here, if you don't have some accounts just comment them
    a-envelope = "mailto:your@email.com"
    b-stack-overflow ="https://stackoverflow.com/users/12345678/john-doe"
    c-twitter = "https://twitter.com/johndoe"
    d-facebook = "https://www.facebook.com/johndoe"
    e-github = "https://github.com/johndoe"
    f-youtube = "https://www.youtube.com/channel/12345678"
    g-linkedin = "https://www.linkedin.com/johndoe"
    h-google = "https://plus.google.com/12345678"
    i-github = "https://github.com/johndoe"
    j-weibo = "https://weibo.com" 
    k-weixin = "http://localhost:1313" 
    l-tumblr = "https://www.tumblr.com/blog/johndoe"
    m-instagram = "https://instagram.com/johndoe"
    n-gitlab = "https://gitlab.com/johndoe"
    o-pinterest = "https://www.pinterest.com/johndoe/"
   
    
    
